# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - GOPROXY=https://proxy.golang.org
  - GO111MODULE=on
before:
  hooks:
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
-
  env:
  - CGO_ENABLED=0
  ldflags: -s -w -X main.GitBranch=master -X main.GitCommit=v{{.Version}}-{{.ShortCommit}} -X main.BuildDate={{.Date}}
  goos:
    - linux
    - darwin
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  goarm:
    - 5
    - 6
    - 7
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
    - goos: windows
      format: zip

        #release:
        #  github:
        #    owner: squarescale
        #    name: hssh

        #brews:
        #  - github:
        #      owner: squarescale
        #      name: homebrew-hssh
