on:
  push:
    tags:
      - v0.*.*
name: Release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.18
      - name: Checkout code in Go module directory
        uses: actions/checkout@master
      - name: Check GITHUB_REF environment variable value
        run: echo $GITHUB_REF
      - name: Check environment
        run: env
      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@master
        env:
          GORELEASER_GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
        with:
          args: release --rm-dist
